#!/usr/bin/env python
import os
import time
import subprocess
import shutil

attempt = 100
interval = 0.1

def count_dev_input():
    return len(os.listdir("/dev/input"))

def main():
    original_dev_count = count_dev_input()
    print(f"Original count of files in /dev/input = {original_dev_count}")

    failure_count = 0
    success_count = 0

    shutil.rmtree("logs")
    os.mkdir("logs")

    for i in range(attempt):
        with open(f"logs/{i:02}", "w") as log_file:
            dmesg = subprocess.Popen(["sudo", "dmesg", "-W"], stdin=subprocess.DEVNULL, stdout=log_file, stderr=subprocess.DEVNULL)

            subprocess.run(["sudo", "modprobe", "-v", "-r", "i2c_hid_acpi"])
            subprocess.run(["sudo", "modprobe", "-v", "-r", "i2c_hid"])
            time.sleep(interval)

            subprocess.run(["sudo", "modprobe", "-v", "./hid/drivers/hid/i2c-hid/i2c-hid.ko", "dyndbg==pmf"])
            subprocess.run(["sudo", "modprobe", "-v", "./hid/drivers/hid/i2c-hid/i2c-hid-acpi.ko", "dyndbg==pmf"])
            time.sleep(interval)

            dmesg.terminate()

            current_dev_count = count_dev_input()
            print(f"Current count of files in /dev/input = {current_dev_count}")

            if current_dev_count == original_dev_count:
                success_count += 1
                os.rename(f"logs/{i:02}", f"logs/{i:02}-success")
            else:
                failure_count += 1
                os.rename(f"logs/{i:02}", f"logs/{i:02}-failure")

    subprocess.run(["sudo", "modprobe", "-v", "-r", "i2c_hid_acpi"])
    subprocess.run(["sudo", "modprobe", "-v", "-r", "i2c_hid"])
    time.sleep(interval)

    subprocess.run(["sudo", "modprobe", "-v", "i2c_hid_acpi"])
    subprocess.run(["sudo", "modprobe", "-v", "i2c_hid"])
    time.sleep(interval)

    print(f"Final success rate ({success_count}/{attempt})")

if __name__ == "__main__":
    main()

